//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_shopping_management1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_table
    {
        public int adid { get; set; }
        public string admin_Email { get; set; }
        public string Pass { get; set; }
    }
}
