//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_shopping_management1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class online_stationaryEntities1 : DbContext
    {
        public online_stationaryEntities1()
            : base("name=online_stationaryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_table> admin_table { get; set; }
        public virtual DbSet<Emp> Emps { get; set; }
        public virtual DbSet<Stat> Stats { get; set; }
        public virtual DbSet<Stationary> Stationaries { get; set; }
        public virtual DbSet<Order_table> Order_table { get; set; }
    }
}
